# Generated by Django 3.1.3 on 2020-12-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0003_auto_20201210_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='asignee',
            new_name='assignee',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
