# Generated by Django 3.1.3 on 2021-01-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0004_auto_20201210_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('i', 'In progress'), ('s', 'Started'), ('r', 'Review'), ('c', 'Completed')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
