# Generated by Django 3.1.3 on 2021-01-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_owner'),
        ('taskboard', '0005_auto_20210104_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='taskboard',
            name='team',
        ),
        migrations.AddField(
            model_name='taskboard',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
