# Generated by Django 3.1.3 on 2021-01-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0006_auto_20210126_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskboard.taskboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('b', 'Backlog'), ('i', 'In progress'), ('r', 'Review'), ('c', 'Completed')], max_length=1),
        ),
    ]
